# Generated by Django 4.2.5 on 2023-10-10 18:49

from django.db import migrations
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('superpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpage',
            name='content',
            field=wagtail.fields.StreamField([('subheader', wagtail.blocks.CharBlock(help_text='Section subheader', reqired=False)), ('section_text_and_image', wagtail.blocks.StructBlock([('section_image', wagtail.images.blocks.ImageChooserBlock('wagtailimages.Image', blank=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+')), ('section_text', wagtail.blocks.RichTextBlock(blank=True, help_text='Section text', null=True))])), ('section_text', wagtail.blocks.RichTextBlock(blank=True, help_text='Section text', null=True)), ('section_carousel', wagtail.blocks.StructBlock([('slides', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('slide_image', wagtail.images.blocks.ImageChooserBlock('wagtailimages.Image', blank=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+'))]))), ('slide_text', wagtail.blocks.CharBlock(blank=True, max_length=100, null=True, required=False)), ('button_text', wagtail.blocks.CharBlock(blank=True, max_length=100, null=True, required=False)), ('button_link', wagtail.blocks.URLBlock(blank=True, max_length=200, null=True, required=False))], help_text='Section slider'))], blank=True, null=True, use_json_field=True),
        ),
    ]
