# Generated by Django 4.2.5 on 2023-10-02 18:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('body', wagtail.fields.RichTextField(blank=True, null=True)),
                ('offices', wagtail.fields.StreamField([('office', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('office_name', wagtail.blocks.CharBlock(blank=True, max_length=200, null=True, required=True)), ('office_type', wagtail.blocks.CharBlock(blank=True, max_length=200, null=True, required=True))])))], blank=True, null=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
