# Generated by Django 4.2.5 on 2023-10-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('contacts', '0002_contactpage_formfield_delete_contactspage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPage',
            new_name='ContactsPage',
        ),
    ]
