# Generated by Django 4.2.5 on 2023-11-06 22:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contactspage_offices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactspage',
            name='offices',
            field=wagtail.fields.StreamField([('office', wagtail.blocks.StructBlock([('office_name', wagtail.blocks.CharBlock(blank=True, max_length=200, null=True, required=True)), ('office_phone', wagtail.blocks.CharBlock(blank=True, max_length=200, null=True, required=False)), ('office_location', wagtail.blocks.CharBlock(blank=True, max_length=200, null=True, required=False)), ('office_province', wagtail.blocks.CharBlock(blank=True, max_length=200, null=True, required=False)), ('office_comment', wagtail.blocks.RichTextBlock(blank=True, max_length=200, null=True, required=False)), ('lat', wagtail.blocks.CharBlock(blank=True, max_length=200, null=True, required=True)), ('lng', wagtail.blocks.CharBlock(blank=True, max_length=200, null=True, required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
