# Generated by Django 4.2.5 on 2023-10-08 18:28

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_alter_releasepage_release_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasepage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releasespage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
