# Generated by Django 4.2.5 on 2023-10-08 18:33

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_releasepage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasepage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
