# Generated by Django 4.2.5 on 2023-10-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0006_alter_releasepage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasepage',
            name='featured',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
