# Generated by Django 4.2.5 on 2023-10-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0007_releasepage_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasepage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Event date'),
        ),
    ]
