# Generated by Django 4.2.5 on 2023-09-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0004_aboutpage_homepage_bannertext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='bannerText',
            new_name='banner_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_cta',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_cta_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
