# Generated by Django 4.2.5 on 2023-09-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_bannertext_homepage_banner_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
