# Generated by Django 4.2.5 on 2023-09-25 13:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='questions_and_answers',
            field=wagtail.fields.StreamField([('question_and_answer', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(help_text='Dropdown header', reqired=True)), ('contnent', wagtail.blocks.TextBlock(help_text='Dropdown content', reqired=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
