# Generated by Django 4.2.5 on 2023-09-25 15:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpage_body_aboutpage_questions_and_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='questions_and_answers',
            field=wagtail.fields.StreamField([('question_and_answer', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(help_text='Dropdown header', reqired=True)), ('contnent', wagtail.blocks.RichTextBlock(blank=True, help_text='Dropdown content', null=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
