# Generated by Django 4.2.5 on 2023-09-27 22:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook Url', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter Url', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Youtube Url', null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone', max_length=100, null=True)),
                ('email', models.CharField(blank=True, help_text='Contact email', max_length=100, null=True)),
                ('address', models.CharField(blank=True, help_text='Contact address', max_length=200, null=True)),
                ('links', wagtail.fields.StreamField([('link_text', wagtail.blocks.CharBlock(blank=True, max_length=100, null=True, required=True)), ('link_url', wagtail.blocks.URLBlock(blank=True, max_length=300, null=True, required=True))], blank=True, null=True, use_json_field=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
