# Generated by Django 4.2.5 on 2023-09-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_globalsitesettings_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsitesettings',
            name='logo',
            field=models.ImageField(help_text='Logo', null=True, upload_to=''),
        ),
    ]
