# Generated by Django 4.2.5 on 2023-10-10 20:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('site_settings', '0005_alter_globalsitesettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning', wagtail.fields.RichTextField(blank=True, help_text='Warning text', null=True)),
                ('email', models.BooleanField(default=False, help_text='Warning active')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
