# Generated by Django 4.2.5 on 2023-10-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_warningsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warningsettings',
            old_name='email',
            new_name='active',
        ),
    ]
